<a href="https://colab.research.google.com/github/bergmelvin/Sudoku_Solver/blob/main/Sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import requests 

In [ ]:
r = requests.get('https://sugoku.herokuapp.com/board?difficulty=easy')
board = r.json()['board']
print(np.matrix(board))

# y = 5
# x = 2

[[0 0 0 0 7 0 0 0 3]
 [0 0 3 0 0 9 0 7 8]
 [6 7 9 3 0 0 0 0 4]
 [2 0 5 6 0 0 7 0 9]
 [0 4 6 0 9 7 2 1 5]
 [7 9 0 2 0 0 3 0 0]
 [0 3 1 0 8 6 9 0 0]
 [8 0 0 0 0 0 4 6 1]
 [0 0 0 0 0 0 0 0 7]]


In [ ]:
def possible(y, x, num):
  # Check row
  for i in range(9):
    if board[y][i] == num:
      return False
  
  # Check column
  for i in range(9):
    if board[i][x] == num:
      return False
  
  # Check square
  y0 = (y//3)*3
  x0 = (x//3)*3

  for i in range(3):
    for j in range(3):
      if board[y0+i][x0+j] == num:
        return False
  
  return True

In [ ]:
def solve():
  global board
  for y in range(9):
    for x in range(9):
      if board[y][x] == 0:
        for num in range(1,10):
          if possible(y,x,num):
            board[y][x] = num
            solve()
            board[y][x] = 0
        return
  print(np.matrix(board))
  input("More?")

In [ ]:
solve()

[[1 8 4 5 7 2 6 9 3]
 [5 2 3 4 6 9 1 7 8]
 [6 7 9 3 1 8 5 2 4]
 [2 1 5 6 3 4 7 8 9]
 [3 4 6 8 9 7 2 1 5]
 [7 9 8 2 5 1 3 4 6]
 [4 3 1 7 8 6 9 5 2]
 [8 5 7 9 2 3 4 6 1]
 [9 6 2 1 4 5 8 3 7]]
More?
[[5 8 4 1 7 2 6 9 3]
 [1 2 3 4 6 9 5 7 8]
 [6 7 9 3 5 8 1 2 4]
 [2 1 5 6 3 4 7 8 9]
 [3 4 6 8 9 7 2 1 5]
 [7 9 8 2 1 5 3 4 6]
 [4 3 1 7 8 6 9 5 2]
 [8 5 7 9 2 3 4 6 1]
 [9 6 2 5 4 1 8 3 7]]
More?
